Feature
Jmagero/apple-clone pull request #1
Opened 2020-03-16 22:01 UTC by Jmagero

2020-03-16 23:00 UTC, majovanilla commented
# Code Review in progress 👀 by Maria Reyes

2020-03-16 23:49 UTC, majovanilla requested changes
Hey @Jmagero , 👋

## Good job on this project! 👍

- Good Readme file

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

-Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) And ALWAYS include a message in your PR.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔
- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-16 23:49 UTC, majovanilla commented on README.md
> +> This project is a clone of apple webpage.
- [ ] Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...

- [ ] Delete the section that you are not using.

2020-03-16 23:49 UTC, majovanilla commented on index.html
> +    <main>
- [ ] Your project is not behaving like the original page. It should be centered on the screen (including the `aside` and the `footer`. You can **start** giving width to your body and then using `margin: auto` to center it and then arranging the rest.

2020-03-16 23:49 UTC, majovanilla commented on index.html
> +        </aside>
- [ ] This section is aligned to the left side of the page, but it should be centered and aligned with the main background image.
![Screenshot from 2020-03-16 17-20-26](https://user-images.githubusercontent.com/51926937/76807594-7ac42e80-67aa-11ea-9e6d-eec45971b469.png)

You might not be able to see this due to your smaller screen, that's why the importance of giving the body a width (less than 100%)

2020-03-16 23:49 UTC, majovanilla commented on index.html
> +            </nav>
- [ ]  Read this [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) and this [question](https://stackoverflow.com/questions/21715162/when-should-i-use-a-button-button-or-a-link-a-in-html) about the use of buttons. You shouldn't use them the way you are using them right now (please apply the above advice to change them).

- [ ]  The `nav` tag shouldn't be inside the `main` tag. It should be before.

2020-03-16 23:49 UTC, majovanilla commented on index.html
> +        </aside>
- [ ] The elements should be links like the original page.

2020-03-16 23:49 UTC, majovanilla commented on styles/style.css
> +}
- [ ] you don't need the padding here. It creates a space above the aside section that shouldn't be there.

2020-03-16 23:49 UTC, majovanilla commented on index.html
> +            </div>
- [ ] This second footer should be aligned to the left with the `first-footer` and it's not. See image:
![Screenshot from 2020-03-16 17-41-43](https://user-images.githubusercontent.com/51926937/76808444-6cc3dd00-67ad-11ea-95a8-3a2deae50acc.png)

2020-03-16 23:49 UTC, majovanilla commented on index.html
> +        </div>
- [ ] These elements are links. If you check the original page you can see there is no need to write the text, you can just copy the images and position them. Choose an option, but make sure they are clickable and that the look is the same (they should have more space between them)

2020-03-18 16:25 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

2020-03-18 16:27 UTC, Oluwadamilareolusakin commented
#### Full-width site
Please consider that the original site is full

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review. 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-03-20 07:49 UTC, addod19 requested changes
## Status: Require changes ♻️ 🚥 

Hi @Jmagero, congratulations on working on the comments of the previous reviewers 👍 We are almost there 👍 We left out some of the comments by the previous TSE. Let us fix the comments below:

* The width of the page should cover the entire window as it is in the original. Check images for reference. Currently
![fw1](https://user-images.githubusercontent.com/46388113/77144867-e34b2e00-6a7e-11ea-9656-507d6879fe34.PNG)
```Original```
![fw](https://user-images.githubusercontent.com/46388113/77144887-f100b380-6a7e-11ea-9137-2a1ae40d8933.PNG)
* Let us work on the nav a little bit. Let us apply 2 shades of color to the nav as it is in the original and center the nav

Kindly apply these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Find me on slack Daniel Larbi Addo

2020-03-20 17:23 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo

2020-03-20 17:24 UTC, addod19 approved these changes
## Status: Approved 🏆 🎈 

Hi @Jmagero, **Congratulations** on the great job 👌 You did 👍  implement all the changes requested by the previous TSE'S. Our project now meets all the minimum requirements. I hereby approve of the project. Go ahead and merge to master and submit project completion form 👍 

Good luck with your next projects ⚙️ 
_Happy coding_ 👩‍💻 
Daniel Larbi Addo

2020-03-20 17:25 UTC, Jmagero commented
Thanks Daniel

On Fri, Mar 20, 2020 at 8:24 PM Daniel Larbi Addo <notifications@github.com>
wrote:

> *@addod19* approved this pull request.
> Status: Approved 🏆 🎈
>
> Hi @Jmagero <https://github.com/Jmagero>, *Congratulations* on the great
> job 👌 You did 👍 implement all the changes requested by the previous
> TSE'S. Our project now meets all the minimum requirements. I hereby approve
> of the project. Go ahead and merge to master and submit project completion
> form 👍
>
> Good luck with your next projects ⚙️
> *Happy coding* 👩‍💻
> Daniel Larbi Addo
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Jmagero/apple-clone/pull/1#pullrequestreview-378675882>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMNPKWT2FMYEFC4IJ7H3T73RIORD7ANCNFSM4LMWX5AQ>
> .
>

2020-03-20 17:27 UTC, merged